///////////////////////////////////////////////////////////
//  Documentos.cs
//  Implementation of the Class Documentos
//  Generated by Enterprise Architect
//  Created on:      03-Apr-2020 9:59:55 PM
//  Original author: Gustavo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace GoHorseClassLibrary
{
	public class Documentos
	{

		private int IdPessoa;
		private string Rg;
		private string Cpf;
		private string CnhRegistro;
		private string CnhValidade;
		private string CnhCategoria;

		public Documentos()
		{

		}

		~Documentos()
		{

		}

		/// 
		/// <param name="Id"></param>
		public void GetRg(int Id)
		{

		}

		/// 
		/// <param name="Id"></param>
		public void GetCpf(int Id)
		{

		}

		/// 
		/// <param name="Id"></param>
		public void GetCnhRegistro(int Id)
		{

		}

		/// 
		/// <param name="Id"></param>
		public void GetCnhValidade(int Id)
		{

		}

		/// 
		/// <param name="Id"></param>
		public void GetCnhCategoria(int Id)
		{

		}

		/// 
		/// <param name="Id"></param>
		public void SetRg(int Id)
		{

		}

		/// 
		/// <param name="Id"></param>
		public void SetCpf(int Id)
		{

		}

		/// 
		/// <param name="Id"></param>
		public void SetCnhRegistro(int Id)
		{

		}

		/// 
		/// <param name="Id"></param>
		public void SetCnhValidade(int Id)
		{

		}

		/// 
		/// <param name="Id"></param>
		public void SetCnhCategoria(int Id)
		{

		}

	}//end Documentos
}