///////////////////////////////////////////////////////////
//  NumTel.cs
//  Implementation of the Class NumTel
//  Generated by Enterprise Architect
//  Created on:      03-Apr-2020 10:00:01 PM
//  Original author: Gustavo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace GoHorseClassLibrary
{
	public class NumTel
	{

		private int IdPessoa;
		private int Numero;

		public NumTel()
		{

		}

		~NumTel()
		{

		}

	}//end NumTel
}